# Generated by Django 5.2.9 on 2025-12-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='region',
            field=models.CharField(blank=True, choices=[('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('대전', '대전'), ('세종', '세종'), ('충남', '충남'), ('충북', '충북'), ('광주', '광주'), ('전남', '전남'), ('전북', '전북'), ('대구', '대구'), ('경북', '경북'), ('부산', '부산'), ('울산', '울산'), ('경남', '경남'), ('강원', '강원'), ('제주', '제주')], default='', max_length=20, null=True),
        ),
    ]
